# Generated by Django 2.2 on 2019-07-15 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sabteahval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('person_father_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Father Name')),
                ('person_shen_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='Shenasname Code')),
                ('person_born_date', models.CharField(blank=True, max_length=32, null=True, verbose_name='Birthday')),
                ('person_melli_code', models.CharField(max_length=32, verbose_name='Melli Code')),
                ('mobile_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mobile Number')),
            ],
            options={
                'verbose_name': 'Sabteahval',
                'verbose_name_plural': 'Sabteahvals',
            },
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='0', max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='person_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='person_born_date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='user',
            name='person_father_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Father Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='person_gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=16, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='person_melli_code',
            field=models.CharField(max_length=32, verbose_name='Melli Code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='person_shen_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Shenasname Code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sajad_person_id',
            field=models.IntegerField(blank=True, default='0', verbose_name='Sajad Person ID'),
        ),
    ]
