# Generated by Django 2.2 on 2019-07-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_sabteahval_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isargari',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=500, null=True, verbose_name='Isargar'),
        ),
        migrations.AddField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=500, null=True, verbose_name='Marital Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_children',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Children'),
        ),
        migrations.AddField(
            model_name='user',
            name='physical_condition',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=500, null=True, verbose_name='Physical Condition'),
        ),
    ]
