# Generated by Django 2.2 on 2019-07-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190721_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='pic_folder/gender_2.gif', upload_to='static/avatars'),
        ),
    ]
