# Generated by Django 2.2 on 2019-07-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isargari',
            field=models.CharField(blank=True, choices=[('farzand_shahid', 'Farzand Shahid'), ('farzand_azadeh', 'Farzand Azadeh'), ('farzand_janbaz', 'Farzand Janbaz'), ('farzand_razmandeh', 'Farzand Razmandeh'), ('farzand_javidasar', 'Farzand Javidasar'), ('hamsar_shahid', 'Hamsar Shahid'), ('hamsar_azadeh', 'Hamsar Azadeh'), ('hamsar_janbaz', 'Hamsar Janbaz'), ('hamsar_razmandeh', 'Hamsar Razmandeh'), ('hamsar_javidasar', 'Hamsar Javidasar'), ('janbaz', 'Janbaz'), ('azadeh', 'Azadeh'), ('razmandeh', 'Razmandeh'), ('o', 'Other')], max_length=500, null=True, verbose_name='Isargar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('unmarried', 'Unmarried'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('o', 'Other')], max_length=500, null=True, verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='person_gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=16, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='physical_condition',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('deaf', 'Deaf'), ('blind', 'Blind'), ('disabled', 'Disabled'), ('o', 'Other')], max_length=500, null=True, verbose_name='Physical Condition'),
        ),
    ]
