# Generated by Django 2.2 on 2019-07-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190721_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='military',
            field=models.CharField(blank=True, choices=[('farzand_shahid', 'Farzand Shahid'), ('farzand_azadeh', 'Farzand Azadeh'), ('farzand_janbaz', 'Farzand Janbaz'), ('farzand_razmandeh', 'Farzand Razmandeh'), ('farzand_javidasar', 'Farzand Javidasar'), ('hamsar_shahid', 'Hamsar Shahid'), ('hamsar_azadeh', 'Hamsar Azadeh'), ('hamsar_janbaz', 'Hamsar Janbaz'), ('hamsar_razmandeh', 'Hamsar Razmandeh'), ('hamsar_javidasar', 'Hamsar Javidasar'), ('janbaz', 'Janbaz'), ('azadeh', 'Azadeh'), ('razmandeh', 'Razmandeh'), ('o', 'Other')], max_length=500, null=True, verbose_name='Military'),
        ),
        migrations.AlterField(
            model_name='user',
            name='physical_condition',
            field=models.CharField(blank=True, choices=[('healthy', 'Healthy'), ('deaf', 'Deaf'), ('blind', 'Blind'), ('disabled', 'Disability Movement'), ('o', 'Other')], max_length=500, null=True, verbose_name='Physical Condition'),
        ),
    ]
