# Generated by Django 2.2 on 2019-07-15 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='center',
            options={'verbose_name': 'Center', 'verbose_name_plural': 'Centers'},
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'verbose_name': 'Field', 'verbose_name_plural': 'Fields'},
        ),
        migrations.AlterModelOptions(
            name='military',
            options={'verbose_name': 'Military', 'verbose_name_plural': 'Military Types'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('can_see_all_students', 'View all Students'),), 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'verbose_name': 'Term', 'verbose_name_plural': 'Terms'},
        ),
    ]
